services:
  
  detection-api:
    build:
      context: ./detection-api-server
      dockerfile: Dockerfile
    privileged: true
    ports:
      - "8008:8008"  # Adjust the port as needed
    environment:
      - CAMERA=${CAMERA:-opencv}
      - MODULE=${MODULE:-0}
    networks:
      - app-network
    volumes:
      - ./detection-api-server:/app
      - /dev/bus/usb:/dev/bus/usb
      - ${VIDEO_DEVICE:-/dev/video0}:${VIDEO_DEVICE:-/dev/video0}
    devices:
      - /dev/bus/usb
    device_cgroup_rules:
      - 'c 189:* rmw'
    restart: unless-stopped
    # deploy:     # IF resources are too low.
    #   resources:
    #     limits:
    #       cpus: '0.40'



  expression-api:
    build:
      context: ./TechLabs-Expressions-API
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - detection-api
    networks:
      - app-network
    volumes:
      - ./TechLabs-Expressions-API:/app

networks:
  app-network:
    driver: bridge

